---


- name: install nginx
  become: yes
  apt:
   name="nginx"
   state=present 
   update_cache=true
 

- name: Config service nginx
  become: yes
  template: src=default dest=/etc/nginx/sites-enabled/default
