- name: install nginx
  become: yes
  apt:
   name="nginx"
   state=present
   update_cache=true

- name: install php
  apt:
   name="{{ item }}"
   state=present
   update_cache=true
  with_items:
   - php-fpm
   - php-curl
   - php-gd
   - php-intl
   - php-mbstring
   - php-soap
   - php-xml
   - php-xmlrpc
   - php-zip
   - php-mysql
  become: yes

- name: config nginx
  become: yes
  template: src=default dest=/etc/nginx/sites-enabled/default

- name: deploy sosmed
  script: /home/rizalkemas/Downloads/ansible/ansible_playbook/roles/sosialmedia/templates/deploy.sh
